### ISSUE TITLE
Error when .stylelintrc is not found in the project

### ISSUE THREAD

**Issue by Grzegorzsa** [shinnn/vscode-stylelint#203] opened 2018-05-25 08:46 UTC
I constantly receive error messages when I work on projects that do not contain .stylelintrc.

![stylelint](https://user-images.githubusercontent.com/4502422/40535231-c566f694-6008-11e8-8353-a8a1e10a9da5.png)

TypeError: Cannot read property 'objectExpression' of undefined     at path.get.forEach (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:123:11)     at Array.forEach (native)     at enter (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:114:28)     at NodePath._call (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:65:20)     at NodePath.call (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:36:14)     at NodePath.visit (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:100:12)     at TraversalContext.visitQueue (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:142:16)     at TraversalContext.visitSingle (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:102:19)     at TraversalContext.visit (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:182:19)     at Function.traverse.node (C:\Users\grzegorz\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\index.js:106:17)

**Comment by Grzegorzsa** [comment] 2018-05-25 08:46
Sorry wrong plugin

**Comment by Grzegorzsa** [comment] 2018-05-25 08:49
Reopening as this is the plugin that crashes - I do not have any styling in project and error constantly occurs when I work on JavaScript project

![stylelint2](https://user-images.githubusercontent.com/4502422/40535355-2bd82592-6009-11e8-9b41-038eca1242c1.png)

**Comment by Grzegorzsa** [comment] 2018-05-25 08:51
Windows 10 / 64

**Comment by shinnn** [comment] 2018-05-25 10:49
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/202

**Closed by shinnn** 2018-05-25 10:49 UTC
