### ISSUE TITLE
Add support for ignoring files

### ISSUE THREAD

**Issue by sdurnov** [shinnn/vscode-stylelint#151] opened 2018-03-12 15:48 UTC
Right now, it runs agains all files and ignores exlude both from stylelint config and .stylelintignore.
It even shows warnings in HTML

**Comment by shinnn** [comment] 2018-03-12 17:09
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/148

> it runs agains all files

Nah. Read the document before opening new issues.

> ignores exlude both from stylelint config

Nah.

> and .stylelintignore

https://github.com/shinnn/vscode-stylelint/issues/139#issuecomment-365128588

**Closed by shinnn** 2018-03-12 17:09 UTC
Labels: duplicate
