### ISSUE TITLE
Stylelint is reporting errors on JS file

### ISSUE THREAD

**Issue by tonghuashuo** [shinnn/vscode-stylelint#202] opened 2018-05-25 04:44 UTC
Today I found this problem (never before) that stylelint is giving me errors on js files. also it self is reporting Exceptions. (See screenshot below) Restart VSCode did not work.

I'm using VSCode 1.23.1 on latest Mac OS 10.13.4

![image](https://user-images.githubusercontent.com/6594276/40526364-a5f943b0-6018-11e8-974a-afac98ee0a74.png)

**Comment by shinnn** [comment] 2018-05-25 04:45
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/198

**Closed by shinnn** 2018-05-25 04:45 UTC
