### ISSUE TITLE
Allow support for specifying configFile

### ISSUE THREAD

**Issue by joshhills** [shinnn/vscode-stylelint#109] opened 2017-10-12 00:49 UTC
I have a stylelint configuration pre-defined in a 'config' folder, which at present is not found by this extension.

My build process works as I specify [the 'configFile' path as part of the plugin options](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#configfile).

You have 'config' and 'configOverrides' already defined, I would propose a require is made on a file path if provided.

I'm happy to try implementing this if you are busy.

**Comment by shinnn** [comment] 2017-10-12 04:13
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/97

**Closed by shinnn** 2017-10-12 04:13 UTC
Labels: duplicate

**Comment by sebastian-nowak** [comment] 2018-08-27 07:08
@shinnn: if you consider extends the official solution, why don't you put it in the docs?

**Comment by sebastian-nowak** [comment] 2018-08-27 07:09
@shinnn: if extends is the official solution, it should be in the docs.

**Comment by shinnn** [comment] 2018-08-27 08:35
@sebastian-nowak It's already documented in https://stylelint.io/user-guide/configuration/ and the README of this project has a link to it.
