### ISSUE TITLE
The default setting error

### ISSUE THREAD

**Issue by ifyour** [shinnn/vscode-stylelint#150] opened 2018-03-10 16:21 UTC
![image](https://user-images.githubusercontent.com/15377484/37244302-e2ec4b42-24c1-11e8-87de-ec3c484a83d9.png)

I did not make any changes.

**Comment by SnO2WMaN** [comment] 2018-03-10 20:47
![code_2018-03-11_05-45-32](https://user-images.githubusercontent.com/15155608/37246582-6e44a54a-24ef-11e8-95be-7450d804ec18.png)
![code_2018-03-11_05-46-30](https://user-images.githubusercontent.com/15155608/37246595-8f7764be-24ef-11e8-8d36-d0ebf5aa0647.png)

I'm too and i can't ignore .html / .md

**Comment by SnO2WMaN** [comment] 2018-03-10 21:13
コンフィグ`stylelint.enable`を各言語ずつに適応できるように修正よろしくおねがいします。

**Comment by shinnn** [comment] 2018-03-11 01:36
@ifyour Read at least the last issue before submitting a new one https://github.com/shinnn/vscode-stylelint/issues/148. This is not a bug of this extension and should be fixed in the upstream project.

**Comment by shinnn** [comment] 2018-03-11 01:36
> コンフィグstylelint.enableを各言語ずつに適応できるように修正よろしくおねがいします。

(Google translate: "Please modify config 'stylelint.enable` so that it can adapt to each language.")

@SnO2WMaN No thanks. I've already posted a workaround for it https://github.com/shinnn/vscode-stylelint/issues/148.

https://twitter.com/SnO2WMaN/status/972581540961009664

> 相手が日本人だから多分大丈夫だろうとは思うけど酷い日本語だと思う

(Google translate: "I think that probably it will be okay because the opponent is Japanese, but I think it is awful Japanese")

@SnO2WMaN The language you speak itself is not awful. What is awful for me is, actually, your attitude.

**Closed by shinnn** 2018-03-11 01:36 UTC
