### ISSUE TITLE
Cannot read property 'objectExpression' of undefined

### ISSUE THREAD

**Issue by coolow** [shinnn/vscode-stylelint#198] opened 2018-05-24 03:55 UTC
stylelint threw below error when I write javascript codes.
![image](https://user-images.githubusercontent.com/302606/40463707-46c0b5d8-5f49-11e8-8df4-a059f3318f94.png)

you can reproduce it with:
`foo.bar.baz(function () { })`

maybe it is a bug. I expect it be fixed, to avoid the annoying continuous popup.

**Comment by shinnn** [comment] 2018-05-24 04:45
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/195

**Closed by shinnn** 2018-05-24 04:45 UTC
