### ISSUE TITLE
stylelint throws an error "this[node.type] is not a function"

### ISSUE THREAD

**Issue by eralmansouri** [shinnn/vscode-stylelint#216] opened 2018-06-16 15:30 UTC
If I use this code in a React file:

`const pictureStyle = { 
    backgroundImage: `url(${pictureUrl}) `,
  };`

And then use pictureStyle in a div, I get this error: 
`TypeError: this[node.type] is not a function     at Stringifier.stringify (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\stringifier.js:33:24)     at stringify (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\stringify.js:14:9)     at Obj.toString (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\node.js:195:9)     at module.exports (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\stylelint\lib\utils\rawNodeString.js:12:18)     at module.exports (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\stylelint\lib\utils\blockString.js:22:10)     at root.walkDecls.decl (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\stylelint\lib\rules\declaration-empty-line-before\index.js:90:28)     at C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\container.js:188:28     at C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\container.js:144:26     at Obj.each (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\container.js:110:22)     at Obj.walk (C:\Users\Essam\.vscode\extensions\shinnn.stylelint-0.36.3\node_modules\postcss\lib\container.js:143:21)`

I think it has something to do with trying to stringify parent (which I guess doesn't exist when using a 1 liner?).

I couldn't find a solution anywhere.

**Comment by shinnn** [comment] 2018-06-17 06:55
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/200

**Closed by shinnn** 2018-06-17 06:55 UTC
