### ISSUE TITLE
Support config files in subdirectories

### ISSUE THREAD

**Issue by macgyver** [shinnn/vscode-stylelint#103] opened 2017-09-01 17:41 UTC
I'm sure you probably get a lot of these but I'm hoping you can help me figure out what I'm doing wrong.

I've got a `.stylelintrc` file in my project root:
![_stylelintrc_ _learning-machine](https://user-images.githubusercontent.com/1163/29978355-dd55bd88-8f0e-11e7-81fa-7cdc0307f58c.png)

The plugin is installed and enabled, and the user settings match those in the README:
![screen shot 2017-09-01 at 12 12 19 pm](https://user-images.githubusercontent.com/1163/29978368-ebe35f68-8f0e-11e7-9234-912cb588438d.png)

But the linter doesn't indicate any problems or show any output at all as far as I can tell:
![paid-question-chooser_scss_ _learning-machine](https://user-images.githubusercontent.com/1163/29978420-2b5e3d84-8f0f-11e7-80e8-f5b4b3ab7ed6.png)

Can you recommend some steps on how to continue to debug the issue? Thanks!

As an aside, I think I understand the logic of the config file import but it would sure be nice if there were some way for the plugin to indicate which factors were contributing to the active linting rules.

**Comment by shinnn** [comment] 2017-09-01 17:55
This issue is a duplicate of https://github.com/shinnn/vscode-stylelint/issues/80 and fixed in https://github.com/stylelint/stylelint/commit/c2e3de9524d0961b370020d6f48c327258d71ff3. Wait for the stylelint team to publish a new version which includes the fix.

> it would sure be nice if there were some way for the plugin to indicate which factors were contributing to the active linting rules.

If [the result of stylelint API](https://github.com/stylelint/stylelint/blob/fcc9f5fc011e3270577c33ae64bf99a3d36fae1d/docs/user-guide/node-api.md#the-returned-promise) contains the information, I can update vscode-extension to show it.

**Closed** 2017-09-01 17:56 UTC

**Comment by macgyver** [comment] 2017-09-01 18:47
Aaaa.. thank you so much! Sorry for filing a dupe, I searched the open issues and didn't see mine, but maybe I should have checked the closed issues as well.
