### ISSUE TITLE
stylelint throws an errror “Cannot read property 'file' of undefined”

### ISSUE THREAD

**Issue by deiga** [shinnn/vscode-stylelint#236] opened 2018-07-28 15:08 UTC
I'm not quite sure why Stylelint is even running for `.d.ts` files...

https://gist.github.com/deiga/21540afa10c6000cd28ef156e6249c36

**Comment by shinnn** [comment] 2018-07-30 02:21
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/217

**Closed by shinnn** 2018-07-30 02:21 UTC
