### ISSUE TITLE
Allow user to define version of stylelint

### ISSUE THREAD

**Issue by dkniffin** [shinnn/vscode-stylelint#220] opened 2018-06-22 13:00 UTC
There's a very similar open issue (https://github.com/shinnn/vscode-stylelint/issues/4), but it was locked for some unknown reason. I really need this feature, because I work on several different projects on a daily basis, and they all use different versions of stylelint. It's not feasible to change the stylelint version of these projects, just to use this extension.

**Comment by shinnn** [comment] 2018-06-23 01:21
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/4.

**Closed by shinnn** 2018-06-23 01:21 UTC
