### ISSUE TITLE
could you please add configFile option?

### ISSUE THREAD

**Issue by anlexN** [shinnn/vscode-stylelint#97] opened 2017-08-03 11:47 UTC

**Comment by shinnn** [comment] 2017-08-03 12:01
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/57

My answer: https://github.com/shinnn/vscode-stylelint/issues/57#issuecomment-314483411

> PR welcome. I'm not interesting in this feature though.

**Closed by shinnn** 2017-08-03 12:01 UTC
Labels: duplicate
