### ISSUE TITLE
styled-components processor produces a warning without `line` property

### ISSUE THREAD

**Issue by SenHeng** [shinnn/vscode-stylelint#185] opened 2018-05-22 01:53 UTC
Started getting this error today. Any ideas?

```
TypeError: `line` property of a stylelint warning must be a number, but it was undefined.
at stylelintWarningToVscodeDiagnostic (/Users/emp-mac-heng/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/stylelint-warning-to-vscode-diagnostic/index.js:21:10)
at Array.map (native)
at processResults (/Users/emp-mac-heng/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/stylelint-vscode/index.js:60:19)
at stylelintVSCode (/Users/emp-mac-heng/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/stylelint-vscode/index.js:83:9)
at <anonymous>
```

**Comment by shinnn** [comment] 2018-05-22 01:55
duplicate of #164

**Closed by shinnn** 2018-05-22 01:55 UTC
