### ISSUE TITLE
Error with the latest VS Code insiders

### ISSUE THREAD

**Issue by vvs** [shinnn/vscode-stylelint#191] opened 2018-05-22 09:00 UTC
Just upgraded to the latest stylelint (**0.36.2**) and the latest VS Code Insiders.

VS Code version: Code - Insiders 1.24.0-insider (dbd7f09189947497c77755d0738c115d689c680f, 2018-05-22T05:17:48.854Z)
OS version: Windows_NT x64 10.0.16299

I am getting the following error pop-up right after I start VS Code now:

```
TypeError: Cannot read property 'objectExpression' of undefined

at path.get.forEach (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:123:11) 
at Array.forEach (native)
at enter (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:114:28) 
at NodePath._call (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:65:20) 
at NodePath.call (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:36:14) 
at NodePath.visit (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:100:12) 
at TraversalContext.visitQueue (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:142:16) 
at TraversalContext.visitSingle (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:102:19) 
at TraversalContext.visit (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:182:19) 
at Function.traverse.node (C:\Users\vvs\.vscode-insiders\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\index.js:106:17)
```

**Comment by shinnn** [comment] 2018-05-22 09:02
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/190.

**Closed by shinnn** 2018-05-22 09:02 UTC
