### ISSUE TITLE
Add changelog?

### ISSUE THREAD

**Issue by Bigdragon13th** [shinnn/vscode-stylelint#49] opened 2017-02-06 05:48 UTC
Everytime I update all of my plugin, I want to know what is changed. This plugin doesn't provide a changelog so I have to go read in the commit message to get what's going on. Provide a changelog whould be nice.

**Comment by shinnn** [comment] 2017-07-11 15:26
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/21

**Closed by shinnn** 2017-07-11 15:26 UTC
