### ISSUE TITLE
Enhancement: Allow us to override the languages stylelint works on.

### ISSUE THREAD

**Issue by sgarcia-dev** [shinnn/vscode-stylelint#160] opened 2018-03-23 20:49 UTC
I noticed that currently, this package uses an `activationEvents` prop in it's own `package.json` to define what languages are supported, for some people may not want *all* the supported languages to be linted. A good example of this are `.xml` files. A valuable setting could be adding a configurable VS Code setting for `stylelint.disabledLanguages` that would allow us to selectively disable stylelint where we don't want it to work on. Sounds like an easy enhancement. Thoughts @shinnn ?

Example of what I mean:
https://github.com/shinnn/vscode-stylelint/search?utf8=%E2%9C%93&q=activationEvents&type=

**Comment by shinnn** [comment] 2018-03-23 22:14
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/158.

**Closed by shinnn** 2018-03-23 22:14 UTC

**Comment by sgarcia-dev** [comment] 2018-03-28 17:22
Wasn't aware of that! Considering you've had quite a few duplicates, might be a good idea considering to add this to the ReadMe.md (That you can ignore files via `"ignoreFiles": "**/*.anyfileextensionyoudontwanttolint"`)

**Comment by shinnn** [comment] 2018-03-29 09:57
Use [Github search](https://help.github.com/articles/searching-issues-and-pull-requests/) before posting new issues.

> Considering you've had quite a few duplicates...

I'll just close them every time.
