### ISSUE TITLE
TypeError: Cannot read property 'objectExpression' of undefined

### ISSUE THREAD

**Issue by saito1638** [shinnn/vscode-stylelint#206] opened 2018-05-26 07:07 UTC
vscode v1.23.1
vscode-stylelint v0.36.2

.js編集中にエラーが多発。

```
TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:123:11) at Array.forEach
(native) at enter
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:114:28) at NodePath._call
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:65:20) at NodePath.call
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:36:14) at NodePath.visit
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:100:12) at TraversalContext.visitQueue
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/context.js:142:16) at TraversalContext.visitSingle
(/Users/user/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/trave...
```

![2018-05-26 16 04 30](https://user-images.githubusercontent.com/39643542/40573588-8a3f4e9e-60fe-11e8-8eae-bcee24fc2fd5.png)

**Comment by kurtextrem** [comment] 2018-05-26 08:36
I get the same error in JavaScript files. I tried adding `".js"` to `.stylelintignore`, but error still appears when I open JavaScript files.

**Comment by shinnn** [comment] 2018-05-26 08:53
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/204

**Closed by shinnn** 2018-05-26 08:53 UTC
