### ISSUE TITLE
auto fix on save by stuartzhang.stylelint-stzhang

### ISSUE THREAD

**Issue by multics** [shinnn/vscode-stylelint#268] opened 2019-03-21 03:24 UTC
stuartzhang.stylelint-stzhang is a VSCode extension, which forks from this one, and it supports auto fix on save. I hope this "official" one could support auto fix on save as well. Since the similar feature request was 1 year ago, and not sure its status now.

**Comment by shinnn** [comment] 2019-03-21 03:43
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/138

**Closed by shinnn** 2019-03-21 03:43 UTC
