### ISSUE TITLE
Keep popping out TypeError

### ISSUE THREAD

**Issue by mRcfps** [shinnn/vscode-stylelint#204] opened 2018-05-25 08:59 UTC
After I've installed vscode-stylelint, VSCode notifications keep telling me there is `TypeError` in this extension:

```
TypeError: Cannot read property 'objectExpression' of undefined 
at path.get.forEach (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:123:11) 
at Array.forEach (native) at enter (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:114:28) 
at NodePath._call (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:65:20) 
at NodePath.call (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:36:14) 
at NodePath.visit (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:100:12) 
at TraversalContext.visitQueue (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/context.js:142:16) 
at TraversalContext.visitSingle (/Users/mRc/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/contex...

(More stack trace are truncated by vscode)
```

vscode-stylelint: Version 0.36.2
VSCode: 1.23.1

**Comment by shinnn** [comment] 2018-05-25 10:50
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/203

**Closed by shinnn** 2018-05-25 10:50 UTC
