### ISSUE TITLE
Stylelint throws error when opening .js files

### ISSUE THREAD

**Issue by MikaelEdebro** [shinnn/vscode-stylelint#194] opened 2018-05-23 06:58 UTC
This exception is being thrown when opening some .js files:

TypeError: Cannot read property 'objectExpression' of undefined     at path.get.forEach (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:123:11)     at Array.forEach (native)     at enter (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:114:28)     at NodePath._call (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:65:20)     at NodePath.call (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:36:14)     at NodePath.visit (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:100:12)     at TraversalContext.visitQueue (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:142:16)     at TraversalContext.visitSingle (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:102:19)     at TraversalContext.visit (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:182:19)     at Function.traverse.node (C:\Users\Mikael\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\index.js:106:17)

My environment:
Windows 10
Latest Vs Code & stylelint
Node.js 9.5.0

**Comment by pielambr** [comment] 2018-05-23 08:38
Same thing happening to me since today.
I have been using the same working setup for months now, and suddenly stylelint started linting my javascript files.

**Comment by shinnn** [comment] 2018-05-23 08:50
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/192

**Closed by shinnn** 2018-05-23 08:50 UTC
