### ISSUE TITLE
VSCode Stylelint ignores .stylelintignore

### ISSUE THREAD

**Issue by AlesMenzel** [shinnn/vscode-stylelint#139] opened 2018-02-11 14:03 UTC
The extention does not take into account `.stylelintignore` as is from the [stylelint documentation](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#stylelintignore).

Instead `ignoreFiles` must be used in `.stylelintrc` file like:
```
{
  ...
  "ignoreFiles": ["node_modules", "**/*.css"] // Check only SASS files
}
```

**Comment by shinnn** [comment] 2018-02-13 02:11
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/132

**Closed by shinnn** 2018-02-13 02:11 UTC
