### ISSUE TITLE
stylelint.validate setting

### ISSUE THREAD

**Issue by marudor** [shinnn/vscode-stylelint#264] opened 2019-03-05 10:18 UTC
I would like a `stylelint.validate` setting similar to `eslint.validate` to restrict which grammars get linted.

Sometimes stylelint has problems with javascript syntax and I would like to set that on extension level. (Instead of .stylelintignore everywhere)

**Comment by shinnn** [comment] 2019-03-05 18:37
Duplicate of https://github.com/shinnn/vscode-stylelint/pull/219.

> I would like to set that on extension level. 

Use [`stylelint.configOverrides`](https://github.com/shinnn/vscode-stylelint/tree/2be1633d0419d9a34a856deaad13218a76183177#stylelintconfigoverrides) extension setting for this case.

**Closed by shinnn** 2019-03-05 18:37 UTC

**Comment by marudor** [comment] 2019-03-06 09:30
You can't set stylelint.configOverrides in .vscode/settings.json on folder level correctly.
You have to change the scope of that setting.
Otherwise it's not really helpful.

**Comment by shinnn** [comment] 2019-03-06 12:51
What really bothers you is not lack of `stylelint.validate`, but rather

> Sometimes stylelint has problems with javascript syntax

It's more productive for users to improve the upstream [stylelint/stylelint](https://github.com/stylelint/stylelint) project than to implement workarounds in its integration tools. I'm looking forward you to submit a good patch to https://github.com/stylelint/stylelint/pulls.

**Comment by marudor** [comment] 2019-03-06 13:03
Yeah - you're right.
Should probably fix that.
