### ISSUE TITLE
Plugin regulary produces stacktraces

### ISSUE THREAD

**Issue by hkrutzer** [shinnn/vscode-stylelint#217] opened 2018-06-17 18:10 UTC
I am writing Typescript that does not contain any styles. I've added `**/*.ts`to ignoreFiles in stylelintrc.js (which shouldn't even be necessary as I don't use CSS in JS). I still regularly get stacktraces such as this one:

```TypeError: Cannot read property 'file' of undefined at Scope.checkBlockScopedCollisions (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:347:21) at Scope.registerBinding (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:506:16) at Scope.registerDeclaration (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:446:14) at Object.BlockScoped (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:189:28) at Object.newFn (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/visitors.js:230:17) at NodePath._call (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/path/context.js:53:20) at NodePath.call (/Users/hkrutzer/.vscode/extensions/shinnn.stylelint-0.36.3/node...```

**Comment by shinnn** [comment] 2018-06-17 22:06
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/210

**Closed by shinnn** 2018-06-17 22:06 UTC
