### ISSUE TITLE
An error occurred while editing the React.

### ISSUE THREAD

**Issue by caryhgq** [shinnn/vscode-stylelint#193] opened 2018-05-23 01:34 UTC
```
TypeError: Cannot read property 'objectExpression' of undefined
at path.get.forEach (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:123:11)
at Array.forEach (native) 
at enter (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:114:28) 
at NodePath._call (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:65:20)
at NodePath.call (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:36:14)
at NodePath.visit (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:100:12) 
at TraversalContext.visitQueue (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/context.js:142:16)
at TraversalContext.visitSingle (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/context.js:102:19)
at TraversalContext.visit (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/context.js:182:19)
at Function.traverse.node (/Users/cary/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/index.js:106:17)
```
macOS  10.13.4 
node      v10.1.0
vs code 1.23.1

**Comment by VAggrippino** [comment] 2018-05-23 02:19
Duplicate of #188. I'd argue that ticket shouldn't have been closed until the upstream issue is addressed, but I'm nobody.

This is an [upstream issue on postcss-jsx](https://github.com/gucong3000/postcss-jsx/issues/8).

**Comment by shinnn** [comment] 2018-05-23 02:30
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/192

**Closed by shinnn** 2018-05-23 02:30 UTC
