### ISSUE TITLE
Turn off validation for a specific file type

### ISSUE THREAD

**Issue by 0rvar** [shinnn/vscode-stylelint#234] opened 2018-07-17 07:24 UTC
I use stylelint in postcss, and stylelint in vscode. The former only lints css files, but this VSCode plugin also lints javascript files. I would like to disable linting in js files as it does not match our command-line linting.

**Comment by shinnn** [comment] 2018-07-17 14:12
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/233

**Closed by shinnn** 2018-07-17 14:12 UTC
Labels: duplicate
