### ISSUE TITLE
Version 0.36.2 - TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach .vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:123:11) at Array.forEach (native) at enter .vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:114:28) at NodePath._call .vscode/extensions/shinnn.stylelint-0.36.2 at NodePat

### ISSUE THREAD

**Issue by djErock** [shinnn/vscode-stylelint#192] opened 2018-05-22 15:19 UTC
This morning I changed "eslint.autoFixOnSave": true, in VS Code and now vscode-styleint has gone hay wire. Every time a even type code throws the error:

TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach (/Users/eg/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:123:11) at Array.forEach (native) at enter (/Users/eg/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:114:28) at NodePath._call (/Users/eg/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:65:20) at NodePat

I changed it back but it didn't make a difference.

Any ideas here?

**Comment by shinnn** [comment] 2018-05-22 15:30
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/191

**Closed by shinnn** 2018-05-22 15:30 UTC
