### ISSUE TITLE
In non-style file: TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach 

### ISSUE THREAD

**Issue by ethancfchen** [shinnn/vscode-stylelint#190] opened 2018-05-22 08:14 UTC
While I edit my JS file, I keep receive the notification from stylelint:

```
TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach 
```

Add `**/*.js` in my `.stylelintignore` file is not working.

**Comment by shinnn** [comment] 2018-05-22 08:21
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/189.

**Closed by shinnn** 2018-05-22 08:21 UTC
