### ISSUE TITLE
Feature request: set stylelint syntax from VSCode language mode

### ISSUE THREAD

**Issue by cpmsmith** [shinnn/vscode-stylelint#276] opened 2019-07-05 15:12 UTC
In theming semantic-ui-less, I've got a bunch of Less files with the extensions `.variables` and `.overrides`—I've set their language mode in VSCode to Less, which gets stylelint to run in the first place, but it assumes they're CSS because it doesn't recognize the file extension.

**Comment by shinnn** [comment] 2019-07-05 16:20
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/208

**Closed by shinnn** 2019-07-05 16:20 UTC
