### ISSUE TITLE
Question: How to enable stylelint for only *.scss files?

### ISSUE THREAD

**Issue by tomasznapieralski** [shinnn/vscode-stylelint#222] opened 2018-06-25 13:25 UTC
Is there an option to lint only one file type?

Can you tell me what should i set in VS Code Settings, pls?

**Comment by shinnn** [comment] 2018-06-26 00:57
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/173

**Closed by shinnn** 2018-06-26 00:57 UTC
