### ISSUE TITLE
Disable it in not style file

### ISSUE THREAD

**Issue by Airkro** [shinnn/vscode-stylelint#231] opened 2018-07-11 01:53 UTC
For some reason, jsx/svg/others trigger the linter. we need a config just like `  "eslint.validate": [
    "javascript",
    "javascriptreact"
  ]`

**Comment by shinnn** [comment] 2018-07-11 01:55
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/222

**Closed by shinnn** 2018-07-11 01:55 UTC
