### ISSUE TITLE
TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach 

### ISSUE THREAD

**Issue by loadingwyn** [shinnn/vscode-stylelint#189] opened 2018-05-22 07:13 UTC
when open a jsx file, this error occured:
<img width="452" alt="2018-05-22 3 10 32" src="https://user-images.githubusercontent.com/17921180/40347314-69b57146-5dd2-11e8-9e40-ba2ec6cf304f.png">

Even I disabled stylelint, this error still poped up.
<img width="275" alt="2018-05-22 3 13 17" src="https://user-images.githubusercontent.com/17921180/40347389-adfb27d8-5dd2-11e8-8cb6-192e3a9c7ac9.png">

**Comment by shinnn** [comment] 2018-05-22 07:14
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/188.

**Closed by shinnn** 2018-05-22 07:14 UTC
