### ISSUE TITLE
stylelint.* VSCode settings link to nowhere

### ISSUE THREAD

**Issue by Eastegg** [shinnn/vscode-stylelint#228] opened 2018-06-29 06:58 UTC
I'm new for stylelint, I already read the  "README.md" ,I just d'not know how to start it :( ....

operating system: win10 x64
VSCode version: 1.24.1
vscode-stylelint version: 0.37.0

**Comment by shinnn** [comment] 2018-06-29 07:32
duplicate of https://github.com/shinnn/vscode-stylelint/issues/224

**Closed** 2018-06-29 07:33 UTC
