### ISSUE TITLE
Custom path to stylelint config

### ISSUE THREAD

**Issue by sebastian-nowak** [shinnn/vscode-stylelint#241] opened 2018-08-26 17:15 UTC
Hello,

Is there a way to specify a custom path to the stylelint config file? It's a much needed feature.

Regards,
Sebastian

**Comment by shinnn** [comment] 2018-08-27 02:11
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/109

**Closed by shinnn** 2018-08-27 02:11 UTC
