### ISSUE TITLE
Getting false positives in JS/TS

### ISSUE THREAD

**Issue by jethrolarson** [shinnn/vscode-stylelint#275] opened 2019-07-04 00:33 UTC
![Screen Shot 2019-07-03 at 5 31 18 PM](https://user-images.githubusercontent.com/32480/60632109-77257e80-9db8-11e9-9410-c82dca80c373.png)
I'm using `glamor` for css-in-js and this extension is reporting errors incorrectly in that case. I would disable using vscode-stylelint on ts/js files but I don't see that option in the documentation.

**Comment by shinnn** [comment] 2019-07-04 10:33
About JS/TS-related bugs in *stylelint*, not in vscode-stylelint, read https://github.com/shinnn/vscode-stylelint/issues/270#issuecomment-489583589.

About a feature to disable linting for specific file types, use [GitHub issue search](https://help.github.com/en/articles/searching-issues-and-pull-requests). Actually the question is a duplicate of https://github.com/shinnn/vscode-stylelint/issues/263.

**Closed by shinnn** 2019-07-04 10:33 UTC

**Comment by shinnn** [comment] 2019-07-04 10:39
Anyway it’s not recommended to use [glamor](https://github.com/threepointone/glamor) in 2019. ref. https://github.com/threepointone/glamor/issues/360#issuecomment-408376814
