### ISSUE TITLE
error message when opening jsx files via ctrl+p

### ISSUE THREAD

**Issue by fthebaud** [shinnn/vscode-stylelint#195] opened 2018-05-23 09:25 UTC
When I open a jsx file via the quick open command (<kbd>ctrl+p</kbd>), I get the following error message:

`TypeError: Cannot read property 'objectExpression' of undefined     at path.get.forEach (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:123:11)     at Array.forEach (native)     at enter (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-jsx\extract.js:114:28)     at NodePath._call (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:65:20)     at NodePath.call (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:36:14)     at NodePath.visit (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\path\context.js:100:12)     at TraversalContext.visitQueue (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:142:16)     at TraversalContext.visitSingle (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:102:19)     at TraversalContext.visit (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\context.js:182:19)     at Function.traverse.node (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\@babel\traverse\lib\index.js:106:17)`

Or sometimes this message:

`TypeError: this[node.type] is not a function     at Stringifier.stringify (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss\lib\stringifier.js:33:24)     at Stringifier.body (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss\lib\stringifier.js:96:18)     at Stringifier.root (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss\lib\stringifier.js:37:14)     at Stringifier.stringify (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss\lib\stringifier.js:33:24)     at stringify (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss\lib\stringify.js:14:9)     at Root.toString (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss\lib\node.js:195:9)     at checkRoot (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\stylelint\lib\rules\max-empty-lines\index.js:62:31)     at Array.forEach (native)     at module.exports (C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\stylelint\lib\utils\eachRoot.js:13:16)     at C:\Users\fabient\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\stylelint\lib\rules\max-empty-lines\index.js:45:5`

I'm using vscode 1.23.1 (on windows) and stylelint 0.36.2.

**Comment by shinnn** [comment] 2018-05-23 10:17
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/194

**Closed by shinnn** 2018-05-23 10:17 UTC
