### ISSUE TITLE
Turn off validation for a specific file type

### ISSUE THREAD

**Issue by CptLemming** [shinnn/vscode-stylelint#233] opened 2018-07-12 11:06 UTC
Is there any way to prevent `postcss` being run on all file types? I get spammed with the following in the notification area constantly:

![image](https://user-images.githubusercontent.com/2539724/42629331-da23f7ca-85ca-11e8-852e-8f917d71a991.png)

I saw a PR to add this option (#219 ) but it was closed with the suggestion to add a stylelint config file; this isn't always possible (I don't always have control over the projects I'm browsing) and IMO we need a better way to prevent this. As you discounted this idea already, is there a better way to approach this issue? Asking the maintainer of another library you depend on to add support for extra file types again doesn't sound like a maintainable option (if they say no, *your* plugin still throws errors)

**Comment by shinnn** [comment] 2018-07-12 23:55
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/231

**Closed by shinnn** 2018-07-12 23:55 UTC

**Comment by shinnn** [comment] 2018-07-12 23:58
> this isn't always possible (I don't always have control over the projects I'm browsing)

Then use [`stylelint.configOverrides`](https://github.com/shinnn/vscode-stylelint/tree/257076b6c70017ae0c37653e3fb1bb45cadbfdb3#stylelintconfigoverrides) option.
