### ISSUE TITLE
.stylelintignore support

### ISSUE THREAD

**Issue by row1** [shinnn/vscode-stylelint#178] opened 2018-05-09 00:17 UTC
The extension is reporting errors in my SVGs which I want to ignore (not sure why it is looking at SVGs to start with).

I have tried to create a `.stylelintignore` file containing:
```
*.svg
```
But it doesn't seem to be respecting it.

**Comment by shinnn** [comment] 2018-05-09 05:31
Exact duplicate of #167.

**Closed by shinnn** 2018-05-09 05:31 UTC
