### ISSUE TITLE
Older version of postcss-syntax fails to parse SVG

### ISSUE THREAD

**Issue by Sylvert0** [shinnn/vscode-stylelint#232] opened 2018-07-11 21:53 UTC
I have this error when open svg files

```
Error: Cannot find module 'postcss-svg' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at requireSyntax (C:\Users\Sylvert\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\get-syntax.js:31:19) at getSyntax (C:\Users\Sylvert\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\get-syntax.js:50:10) at parser (C:\Users\Sylvert\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\parser.js:37:17) at Object.parse (C:\Users\Sylvert\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\parse.js:19:43) at new LazyResult (C:\Users\Sylvert\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss\lib\lazy-result.js:70:24) at Processor.process (C:\Users\Sylvert\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss\lib\processor.js:117:12)
```

**Comment by shinnn** [comment] 2018-07-11 23:43
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/215

**Closed by shinnn** 2018-07-11 23:43 UTC
